module.exports = [
  "(cocks gun)",
  "100%, Utah!",
  "Good job!",
  "Hi! Johnny Utah.",
  "Your   o'clock appointment is here.",
  "(buzzer)",
  "(buzzer)",
  "Special Agent John Utah, day number one in LA. Welcome aboard.",
  "- Your record's impressive. - Thank you.",
  "You may have been in the top  2% ofyour class at Quantico,...",
  "..but out here you have exactly zero hours of experience in the field.",
  "You know nothing, in fact, less than nothing.",
  "lf you knew you knew nothing, that'd be something, but you don't.",
  "Yes, sir.",
  "- You eat a solid breakfast? - Sir?",
  "All food groups, avoiding caffeine, sugar?",
  "l like my people to be fit. We don't drink and we sure as hell don't smoke!",
  "- Sir, l take the skin off chicken. - Good man!",
  "This is us - Bank Robbery.",
  "You are now in the world's bank robbery capital.",
  "(Utah) 1322 last year in LA County. Up 22% from the year before.",
  "That's correct. We nailed most of them.",
  "Miss Deer, take a look at that for me. Thank you.",
  "D'you know how we nail the bad guys, Utah?",
  "By crunching data, good crime-scene work, good lab work,...",
  "..and, most importantly, good data-based analysis.",
  "Special Agent Utah, are you receiving my signal?",
  "Zero distortion, sir.",
  "l love these things.",
  "You're a real blue-flame special, son: young, dumb and full of cum. l know.",
  "What l don't know is how you got yourself assigned out here to LA with us.",
  "l mean, hell,...",
  "..l guess we must have ourselves an asshole shortage, huh?",
  "Not so far.",
  "OK...",
  "- Pappas? - Yeah?",
  "Put on the blindfold. l want to see you retrieve at least two bricks offthe bottom.",
  "One,...",
  "..two.",
  "(blows whistle)",
  "l've been in the field    years,...",
  "..l've fired my piece over    times in the line of duty.",
  "l got no idea what a blind man fetching bricks from the bottom ofthe pool...",
  "..has got to do with being a special agent.",
  "Added to which indignity, l have been saddled with a blue-flame Quantico cat!",
  "Some quarterback punk. Johnny Unitas or something.",
  "- The shit they pull, huh? - Yeah!",
  "Hey, Angie? Here's your guy!",
  "What?",
  "(sighs) Uh,... Pappas. Angelo Pappas.",
  "Punk. Quarterback punk.",
  "Hm.",
  "Welcome to SeaWorld, kid.",
  "(man) Good luck, Pappas.",
  "Two bricks, comin' up.",
  "(screams)",
  "Little hand says it's time to rock and roll.",
  "- Everybody freeze! - Nobody move! Hands up and eyes down!",
  "Back away from the counters! Hands on your heads now!",
  "Everybody, onto the floor! Move it! Move it!",
  "- Now! Get down! - What's the matter with you people?",
  "You, outta the cubicle. Get outta my way!",
  "Back away and get your fuckin' hands up!",
  "Hey, what's the matter with you? You got earwax?",
  "Back away! Keep your hands where l can see 'em! Hands up!",
  "Hello, hello, ladies and gentlemen. We are the Ex-Presidents!",
  "We need just a few moments ofyour time.",
  "We've been screwing you for years, so a few more seconds shouldn't matter!",
  "On the floor, asshole! The money's insured so it's not worth dying for!",
  "How you doin', Dick?",
  "lmplementing our personal plan of deregulation, Mr President!",
  "- (carhorn) - Time, Mr Carter!",
  "Sixty!",
  "- LBJ? - We're stylin'!",
  "Oh, Ron, l got Nancy on the line!",
  "- (bang) - (woman screams)",
  "Air Force One is waiting, Mr President.",
  "Let's go, let's go, let's go!",
  "Get your hands where l can fuckin' see 'em! Thank you.",
  "Thank you very much. And, please, don't forget to vote!",
  "l'm not a crook!",
  "(gasps)",
  "(Pappas)    banks in three years.",
  "God. ln and out in    seconds!",
  "No-one ever gets shot. Now, what are we talking about here?",
  "We're talking about solid professionals!",
  "Good moves.",
  "Yeah, they control the room well and they stick strictly to the cash drawers.",
  "They don't go for the vault?",
  "No. They never go for the vault. They never get greedy.",
  "Smart. You burn time in the vault.",
  "Reagan usually does the driving.",
  "Stolen switch car, they leave it running. lt looks parked from a distance.",
  "When they run, they dump the vehicle and they vanish.",
  "Like a virgin on prom night.",
  "l mean, they vanish! Pshht!",
  "Surgical. Look at them separate the dye pack.",
  "Dick and Ronnie know theirjobs.",
  "The Ex-Presidents are the best l've ever seen.",
  "Any time you two've finished jerking off, watching MTV, we need to see the tapes.",
  "Pappas, you tell the kid your theory on the Presidents?",
  "Just take the tapes and go, Babbit.",
  "Hang ten, Pappas. Like totally rad, dude!",
  "l tell ya, the department loves it.",
  "What's he talking about, Angelo?",
  "- Found the drop car on Mulholland Drive. - We'll go work it.",
  "(Pappas) Oh, no!",
  "Angelo?",
  "Come on!",
  "Thank you. We'll go work it.",
  "Good.",
  "Excuse me.",
  "l'm working a fuckin' drop car! l don't believe it. Working a drop car!",
  "Pappas - what a hard-on!",
  "- (man # ) Keep away from there. - (man # ) All right.",
  "(men callinstructions)",
  "This car doesn't have AC. Today was a scorcher.",
  "Sweat secretions in the seatbacks.",
  "Are you through, Mr Wizard?",
  "Let me know ifyou find Jimmy Hoffa under the seat while you're at it!",
  "Oh, look at this! lt's  .  . The night is still young.",
  "The way you're going, you'll be able to solve this case and start another one.",
  "Drop car, my ass! Goddamn!",
  "You been working Bank Robbery, what,    years?",
  "Yeah,    years.",
  "LA has changed a lot during that time.",
  "The air got dirty and the sex got clean.",
  "A guy with that much time in must have a theory about these guys.",
  "Leave it alone, Johnny.",
  "OK, fine, you've given up, fine. lt doesn't mean l have to.",
  "Hey! Listen, forget about it, kid. They are ghosts.",
  "Of course. If you couldn't crack it with all your years of experience,...",
  "..it's impossible to think l might have something to offer!",
  "Maybe l can do better than an over-the-hill burnout.",
  "Watch your mouth!",
  "Maybe you should just retire, get some rent-a-cop nightjob and tell 'Nam stories!",
  "Listen! l was taking shrapnel in 'Nam while you were crapping in your hands!",
  "- You mad? - Yeah, l'm mad.",
  "Good and mad?",
  "- Yeah. What you wanna do about it? - Feels good, like you're still alive?",
  "Yeah!",
  "Well, since you're still alive and you're not in the box just yet,...",
  "..why don't you tell me this theory of yours and we'll go get these guys?",
  "OK, hotshot.",
  "You wanna nail the bank robbers and be a big hero?",
  "- Definitely! - Definitely.",
  "Then here it is.",
  "The Ex-Presidents...",
  "..are surfers.",
  "Surfers.",
  "Surfers.",
  "lt's in our face.",
  "Look at the tan line on this guy.",
  "Oh, well, he must be a surfer!",
  "Well, yeah.",
  "Last year, Nixon scuffs the counter when he's going over,...",
  "..so there is a soil sample.",
  "Non-specific mud. Traces of asphalt, traces of oil.",
  "Traces of sand. Carnuba wax.",
  "So l become a wax expert. Now, there's   -some uses for this stuff.",
  "Something like     products.",
  "Candle wax, car wax, moustache wax.",
  "Could be anything.",
  "Guy's waxing his moustache at the beach, gets sand in it,...",
  "..takes it offwith a shoe.",
  "Shoe scuffs the counter...",
  "Would you just shut up a minute! Listen! Maybe you'll learn something.",
  "The lab gave us three possible matches.",
  "This is one ofthem.",
  "- Sex Wax! - Yeah.",
  "You're not into kinky shit, are you?",
  "Not yet! Surfers use this. They rub it on their boards for traction.",
  "Thanks for the tip.",
  "You're welcome for the tip. Here's another.",
  "Check out the dates on these robberies.",
  "lt's strictly a summerjob for these idiots.",
  "Four months.",
  "June to October.",
  "- Same the year before. - That's right. We have one more month.",
  "We won't see 'em till next summer.",
  "They're travelling on the money, going where the waves are.",
  "That's right!",
  "The Ex-Presidents rip off banks to finance their endless summer!",
  "(both) Whoa!",
  "Hey, man, a lot of guys your age are learning to surf.",
  "- lt's cool. There's nothing wrong in it. - l'm   .",
  "That's what l'm saying. lt's never too late.",
  "(boy) Hope you stick with it.",
  "Surfing's the source. lt can change your life.",
  "(Utah) Why can't l just walk around with this thing under my arm...",
  "..and act stoned, ask a few questions?",
  "Well,...",
  "..look.",
  "Look at 'em. They're like some kinda tribe.",
  "They got their own language.",
  "You can'tjust walk up to those guys.",
  "You gotta get out there, learn the moves, get into their head, pick up the speech.",
  "You saying the FBl is going to pay me to learn to surf?",
  "lt's either you or me on the board. Get my drift?",
  "This is for rubber people who don't shave yet.",
  "Come on. You're the quarterbackjock. lt's all balance, right? And co-ordination.",
  "How hard can it be?",
  "(gasps)",
  "(coughs and chokes)",
  "(girl) Hold on!",
  "Hold on.",
  "Use your arms. Paddle. Come on!",
  "lt's all right. Come on. You're OK.",
  "(coughs andsplutters)",
  "You crazy son of a bitch.",
  "You wanna commit suicide, you do it someplace else!",
  "(coughs)",
  "This pig-board piece of shit!",
  "You got no business out here whatsoever!",
  "Hey!",
  "My name's Johnny Utah!",
  "Who cares?!",
  "That is your surfing contact?",
  "''Female, blue eyes, black hair,...",
  "..five foot six,     pounds.''",
  "God, Utah!",
  "Not bad, Utah!",
  "Tyler Ann Endicott, born   .  .  .",
  "(Utah) Exhibition of speed,...",
  "..indecent exposure inside moving vehicle...",
  "Hot, very hot!",
  "What else they got on her?",
  "l still haven't found anything l can use. l gotta find an approach. A way in.",
  "Here we go!",
  "Both parents deceased.",
  "Aeroplane crash, San Diego, '  .",
  "Yeah.",
  "Definitely.",
  "See ya later.",
  "Next?",
  "What do you want?",
  "Shrimp and fries.",
  "l mean, what do you want? Why d'you keep hanging around?",
  "l need you to teach me.",
  "Gimme a break. Shrimp and fries,...",
  "..to go!",
  "Would you like something to drink with that, sir?",
  "- l'm serious! - l can see that you're serious. Forget it.",
  "Stick to... tennis.",
  "l don't know, whatever you do good.",
  "Miniature golf. Your number's   .",
  "You don't understand. l'm gonna learn to surf or break my neck.",
  "What is it? You all of a sudden got this bug that you just have to go surfing?",
  "This is a line, right?",
  "No! No.",
  "See...",
  "My whole life l've done things for other people.",
  "ln high school l played football because my old man expected me to.",
  "Mm-hm.",
  "Then my parents always figured l'd go to law school.",
  "So l did. Football scholarship.",
  "- ls this gonna take a long time? - Wait.",
  "So l'm a big hero to my folks, right?",
  "But two years ago they were killed in a car wreck.",
  "You can't imagine it. Your whole life changes.",
  "And l suddenly realised that all my goals had been their goals,...",
  "..and l hadn't been living my own life, so l wanted something for myself.",
  "So l come out here from Ohio a month ago.",
  "l'd never seen the ocean before. Any ocean.",
  "l never thought it would affect me so much.",
  "l'm drawn to it.",
  "Or something.",
  "l want to do what you do.",
  "lt's the truth.",
  "All right.",
  "OK. Tomorrow.",
  "Here.",
  "am!",
  "lf you are one minute late, l'm gone.",
  "And, stud, l didn't take you on to raise, so...",
  "..l'll teach you a few things and then after that you'll be on your own, OK?",
  "God!",
  "(Tyler) Stop here.",
  "You agree to do exactly what l say when l say it?",
  "Sure.",
  "Pop!",
  "Pop!",
  "You stand straight up, you'll just fall over, so let's try it again.",
  "Start over. Just do it again.",
  "Hey! What ya doin'?",
  "Just do it again. Pop up.",
  "(Tyler) Stay low, you're gonna bite it.",
  "You dragged your knee. You'll wipe out.",
  "You're dragging your foot, you're gonna be fish food.",
  "Both feet have to land on the board at the same time.",
  "That's it. That's it. You're surfing.",
  "(# ''l WillNotFall'' by Wire Train)",
  "Shit!",
  "Doing all right, city boy!",
  "Whoo!",
  "You are surfing!",
  "That's Bodhi.",
  "They call him the Bodhisattva.",
  "He's a modern savage.",
  "He's a real searcher.",
  "- What's he searching for? - The ride! The ultimate ride.",
  "The guy's even crazier than you, Johnny.",
  "Hey!",
  "Heads up!",
  "- Hey! - (screams)",
  "Put me down!",
  "Uh, we know each other.",
  "That's a... a surf board, all right.",
  "Looks like a '   Chevy l used to have!",
  "Tyler, come here.",
  "So, who's the guy? You replace me?",
  "Give me a break. Where you been?",
  "He surfs real well(!)",
  "Come on! He's from Kansas or something.",
  "- He's from Kansas? - Heads up!",
  "(Bodhi) Yeah!",
  "Good catch.",
  "Ready!",
  "Set!",
  "Hut! Hut! Go, let's go, go!",
  "(shouting)",
  "Hut!",
  "Hut!",
  "Hut!",
  "Whose ball is it? Who wants it?",
  "Hut!",
  "Get him!",
  "Get him!",
  "Ready!",
  "Set!",
  "Hut!",
  "What the fuck is wrong with you? Don't you think that's a little out of line?",
  "- Cool it, Roach. Know who this is? - No, l don't!",
  "This is Johnny Utah, Ohio State Buckeyes, all conference. Remember?",
  "Number   how ya doing?",
  "Jesus Christ! Johnny fuckin' Utah! Sorry, man. Didn't mean to get in ya face!",
  "l knew l knew you. lt was the Rose Bowl. Three years ago you beat SC.",
  "- You? You did this? - Yep, him!",
  "- That was one hell of a game. - No shit.",
  "Yeah, but you got nuked in the last quarter.",
  "Yeah, l got my knee folded back about    degrees the wrong way!",
  "- Whoa! That's why you never went pro? - Two years of surgery, missed my window.",
  "Went to law school instead.",
  "Law school! You're a lawyer?",
  "Wow!",
  "Well, life's not over yet, man. You're surfing.",
  "- (man) Lawyers don't surf! - (Bodhi) This one does.",
  "(man) Let's play some football!",
  "(buzzer)",
  "Special Agent Utah, this is not some job flipping burgers at the local drive-in!",
  "Yes, the surfboard bothers me.",
  "Yes, your approach to this whole damn case bothers me.",
  "And, yes, YOU BOTHER ME!",
  "And, Pappas, for the love of Christ,...",
  "..just how the hell did l ever let you talk me into this boneheaded idea?",
  "Harp, we're working undercover. lt takes time. We've produced...",
  "No, no, no, no! Let me tell you what you've produced.",
  "Over the last two weeks you two have produced exactly squat.",
  "SQUAT!",
  "During which time the Ex-Presidents have robbed two more banks!",
  "Now, for Christ's sake,...",
  "..does either one ofyou have anything even remotely interesting to tell me?",
  "Caught my first tube this morning,... sir!",
  "Goddamn it! Why didn't you leave that thing in the car?",
  "lt sticks out so l can't lock it.",
  "Anyway, what's his problem? We're handling our caseload.",
  "- l'm surfing on my own time. - l know, just don't rub Harp's nose in it.",
  "You think l joined the FBl to learn to surf?",
  "This was your lame idea. You gotta back me up on this.",
  "Johnny, we better come up with something real quick.",
  "- My friend... - What?",
  "Encino Savings and Loan. Guard grabbed LBJ's ponytail.",
  " robberies and what do we get from it? One fucking hair.",
  "(Utah) Angelo, pay attention.",
  "There's gonna be a test afterward.",
  "Lab is showing traces oftoxins in the hair. Selenium, titanium, arsenic.",
  "Beaches are always being closed because ofwaste spills.",
  "And surfers are territorial. They stick mostly to certain breaks.",
  "lf we can get hair samples and get a match at a certain beach...",
  "..we'd know which break the Ex-Presidents surf.",
  "You buying this?",
  "No!",
  "No.",
  "But let's do it, anyway.",
  "lt will bug the shit out of Harp.",
  "- My man! - Yeah!",
  "(coughing)",
  "Hey! When you two are done making out, l need to talk to you.",
  "- What's this? Narco entrapment, dude? - Not exactly, dude.",
  "Shit.",
  "Making a wig for my girlfriend. Thank you.",
  "Fuckin' guy's a narc, man.",
  "Dude cut my hair!",
  "So what? He didn't bust us.",
  "He fuckin' cut my hair!",
  "Hey, don't move! Got some huge sucker crawling right into your ear!",
  "Got it!",
  "Leave some fuckin' hair, man!",
  "What is it?",
  "Saved your life, bro. Close one!",
  "PCBs, selenium, titanium, arsenic.",
  "The percentages look right.",
  "Here's a match.",
  "- There's a match? - Latigo Beach.",
  "Nice point break. Long workable rides.",
  "Surf's up, Ace!",
  "Stay off my wave!",
  "Goons trying to drop in.",
  "(# raucous pop music)",
  "Paddle! Paddle! Paddle!",
  "Out ofthe way, you shit!",
  "Hey!",
  "You dinged my board!",
  "Why don't you watch where the fuck you're going!",
  "Politeness counts, asshole!",
  "Go back to the Valley, man!",
  "(laughs)",
  "Angelo, l've eaten shit   times andgot my lights punched outbysome psycho.",
  "There mustbe    guys here with ponytails.",
  "Patience, hotshot. Patience.",
  "lt'll be subtle, if it's here at all. They'll be a group within the group.",
  "These guys are a real tight unit. You'll see 'em, you'll know it.",
  "This the guy?",
  "Yeah.",
  "OK,...",
  "..l know.",
  "This is where you tell me all about how locals rule...",
  "..and yuppie insects like me shouldn't be surfing your break, right?",
  "Nope!",
  "That would be a waste oftime.",
  "We're just gonna fuck you up.",
  "(laughter)",
  "Oh.",
  "Johnny, are you there?",
  "You betternot be trying to pick up anybabes!",
  "Hit him! Yeah! Harder! Yeah!",
  "Back off! He's with me!",
  "Kiss my ass!",
  "Back off. Seriously.",
  "Thank you.",
  "Stay out ofthis, Bodhi.",
  "What's your name?",
  "Bunker.",
  "Bunker. Well, listen, Bunker. l'm actually really glad you found me.",
  "Yeah, why?",
  "Shit!",
  "Come on!",
  "(groaning)",
  "This is stimulating, but we're outta here. Let's go, Utah.",
  "(moaning)",
  "Just keep walking.",
  "Oh!? Uh,... Oh! OK",
  "You two guys seen a kid run through here with a car stereo?",
  "He stole it from me.",
  "No, but there's four guys back there you might wanna check out!",
  "Thanks, buddy!",
  "- Hope you find him. - Don't worry, l will.",
  "You like to start shit, don't you?",
  "Who are those guys?",
  "Nazi assholes.",
  "The guy you dropped is Bunker Weiss,...",
  "..the big one is War Child, AKA Lupton Pitman.",
  "And the other two think they're some kind of death squad around here.",
  "What's their programme?",
  "Brains are wired wrong, they're into bad shit.",
  "Like what? lllegal shit?",
  "Maybe, l don't know. That's not what l'm talking about.",
  "They only live to get radical.",
  "They don't understand the sea, so they'll never get the spiritual side of it.",
  "You're not gonna start chanting or anything, are ya?!",
  "(laughs) l might!",
  "This is me.",
  "So, uh, you still haven't figured out what riding waves is all about, have you?",
  "lt's a state of mind.",
  "lt's that place where you lose yourself and find yourself.",
  "You don't know it yet, but you've got it.",
  "l saw you with those guys, you're a pit bull. They didn't back you down an inch.",
  "- And that is very rare in this world. - Thanks for stepping in.",
  "De nada! Later!",
  "Oh, hey. l'm having some people over at my house tonight ifyou wanna come.",
  "Sure. Where?",
  "- Come with Tyler. She knows. - All right.",
  "Next time you leave your piece and shield in the car, stay in sight! OK?",
  "OK, Dad.",
  "(shouting, rock music blaring)",
  "Yeah, l need you to run a plate for me.",
  "Two Denver four Sam niner five niner, late-Seventies Jeep.",
  "(shouting)",
  "The jeep belongs to a Bunker Weiss, my buddy. Guy's got quite a sheet.",
  "Yeah. Skip all that. Give me the greatest hits.",
  "(music off)",
  "Felony: possession of cocaine - good. Felony: B & E - three months in juvey.",
  "Felony: assault - postgraduate work at Chino. Excellent! l'm loving it!",
  "(Utah) These guys really fit the profile.",
  "l say we lay it on Harp.",
  "(rock music, laughing, shouting)",
  "(Utah) Here comes the night shift.",
  "This is bullshit. This is a bullshit lead. This is totally bullshit.",
  "Harp must be fuckin' desperate if he's listening to you two flakes.",
  "See you bright and early, guys.",
  "Yeah, right(!)",
  "Cold pizza for you. lt's good for breakfast. See you.",
  "(Utah) When did Harp say we'd get the warrant?",
  "First thing. Get some sleep. This could be an interesting morning.",
  "- Hey! - Hey, Bodhi.",
  "l taught him that trick.",
  "l like it!",
  "Watch yourself. She's a wild one.",
  "Make yourself at home. What's mine is yours.",
  "Man, itjacks up.",
  "You drop down into the pit. lt's    feet straight down...",
  "..and your balls, man, your balls are about this big.",
  "And the whole thing's fuckin' roaring.",
  "Pushing you forward, like you're on a freight train or something.",
  "Yeah, and ifyou lose it, the fish'll be picking you out ofthe coral.",
  "Big-wave riding's for macho assholes with a death wish.",
  "No, it's not. lt's the ultimate rush.",
  "There's nothing that comes close to it.",
  "Not even sex.",
  "Maybe that's cos you're not doing it right, Roach.",
  "Just paddling out in a big surf is total commitment.",
  "You can'tjust call time-out if you don't like the way things are going.",
  "So, what's biggest? Waimea?",
  "- Ridden? - Yeah.",
  "McCaha.",
  "Dana Point.",
  "Bells Beach, Australia.",
  "No way Bells is bigger than Waimea, bro.",
  "lt will be next year.",
  "Bodhi believes the   -year storm is coming next year.",
  "-year storm. What's that?",
  "That's kind of a legend.",
  "No, it's real. lt's absolutely real.",
  "Everything moves in cycles,...",
  "..so twice a century the ocean let's us knowjust how small we really are.",
  "A storm comes out ofAntarctica, tearing up the Pacific,...",
  "..and it sends a huge swell north      miles.",
  "And when it hits Bells Beach it'll turn into the biggest surfthis planet has ever seen.",
  "And l will be there.",
  "So will l.",
  "(all whoop andyell)",
  "lf you want the ultimate, you gotta be willing to pay the ultimate price.",
  "lt's not tragic to die doing what you love.",
  "lt's how l want to go.",
  "l ain't gonna live to see   !",
  "There's too much testosterone here!",
  "(laughter)",
  "(Tyler) Bunch of goddamn adrenaline junkies.",
  "Hope you're not buying into this banzai bullshit like the rest of Bodhi's moonies!",
  "What are you talking about?",
  "You've got that kamikaze look, Johnny. l've seen it.",
  "Bodhi can smell it a mile away.",
  "He'll take you to the edge.",
  "Past it.",
  "- Hey, Bodhi. - Johnny has his own demons. Don't you?",
  "(laughter and whooping)",
  "What's going on?",
  "Here. A stealth mission. You up for it?",
  "- Let's do it! - (man) Let's go!",
  "l can barely do this in broad daylight!",
  "Come on. At least nobody's gonna see how bad you are.",
  "- (Tyler) l don't think he's ready for this. - (Bodhi) He'll be fine.",
  "Shit!",
  "Shit! Shit!",
  "Fuck!",
  "(Utah) l gotta be fuckin' crazy!",
  "But are you crazy enough?",
  "Yaaaaaa-hoooooo!",
  "Whooooo-hooooo!",
  "Can't see shit out here. l'm gonna die.",
  "Feel what the wave is doing, then accept its energy.",
  "Get in sync, then charge with it.",
  "- You don't need to see. - Yeah. Vision is overrated(!)",
  "OK, Johnny, this one's got your number on it. Let's jam! Now paddle!",
  "Shit! l'm gonna die now. l'm gonna fuckin' die now.",
  "Fuck...!",
  "Whoo! You're surfing, man!",
  "Whaaaaaaaah!",
  "l'm fuckin' surfin'!",
  "Yeah!",
  "Check it out!",
  "ls this not the best feeling on earth?",
  "Yeah!",
  "Whoo!",
  "Good break, Johnny.",
  "All right!",
  "Yeah.",
  "- Looks like we lost somebody! - Yeah, leave the fire for them.",
  "(man) You wanna get something to eat?",
  "- l'm dying. - l'm starving.",
  "(man) Where's my clothes? You seen my clothes?",
  "Had enough?",
  "Yeah.",
  "l just wanna sit out here for a minute.",
  "Look at you.",
  "What?",
  "Usually you have this intense sort of scowl of concentration on your face,...",
  "..like you're doing all this for a school project or something.",
  "Or like you've got something driving you.",
  "Look - it's gone.",
  "lf l didn't know better,...",
  "..l'd say you looked almost happy.",
  "l can't describe what l'm feeling.",
  "You don't have to.",
  "Goose bumps.",
  "Yeah, it's cold.",
  "Come here.",
  "Holy shit!",
  "- (Tyler) What? - Shit!",
  "l'm really late.",
  "l'm really late!",
  "Holy shit!",
  "Shit! Oh, SHlT!",
  "l'm really late.",
  "(laughs)",
  "(tyres screech)",
  "You guys need any help?",
  "l can't believe you're late to your own raid! What a flake!",
  "Has that worthless punk partner of mine shown up?",
  "- Right here. - Good ofyou to show up, hotshot(!)",
  "Ow! You're gonna tear my skin!",
  "l'm ready to rock, Angelo. Where d'you want me?",
  "Here's how it is.",
  "Babbit and Alvarez are gonna go in the back door. Cullen's gonna back me up.",
  "l wantyou at the side window.",
  "You're strictlyback-up. l don't wanna burn your cover. You got that?",
  "- Got it. - Good.",
  "Now take your position. lt's show time.",
  "Go.",
  "Asshole!",
  "Scooby? Come on, Scooby. (whistles)",
  "(whistles) Scooby, where are you?",
  "- Seen a dog? - No, man.",
  "No dog? Scooby, come on.",
  "Here, Scooby? Scooby?",
  "(TV backgroundmusic)",
  "(click as motorstarts)",
  "What the fu...?",
  "Get your gun. There's someone at the front door! Now!",
  "Yeah, what?",
  "Oh... hi! Oh! Have you seen my dog? lt's a cockapoo-like thing.",
  "l don't know anything about your dog.",
  "Wait!",
  "(mower)",
  "Cullen, this is Utah. Get Angelo out. They're pulling out a fuckin' arsenal.",
  "Utah, repeat, say again.",
  "(loud engine)",
  "Cullen, you copy?",
  "Cullen? Alvarez?",
  "Don't let him pull his badge.",
  "Fuck! l can't hearjack shit over the lawnmower. Christ!",
  "Something's going down, man. This ain't right.",
  "Chill the fuck out, man. lt's nothing.",
  "Will you shut the fuck up! Check the windows, bro, do it!",
  "(Angelo) ..and the little bastard ran off.",
  "- (girl) l know nothing about a fuckin' dog! - Hide the shit!",
  "- You sure it's not in the back yard? - l ain't got time for this!",
  "There's two guys out the back! Duck down.",
  "Oh, shit! shit! We're fucked!",
  "That fuck comes through the door, l'm gonna pump him up, man.",
  "- You sure he's not in the back? - He ain't back here.",
  "- Anybody else around who's seen him? - Get the fuck outta my face!",
  "FBl, gorgeous!",
  "FBl, DROP lT!",
  "Fuck you!",
  "(scream)",
  "Fuckin' pigs!",
  "(screaming)",
  "No, wait! Hey...",
  "Get off... motherfucker!",
  "Shut up!",
  "- You motherfuckers! - Shut up, l said!",
  "Dumb motherfuckers!",
  "(shouting andscreaming)",
  "l'm coming out right now! Back up! Back up!",
  "(screaming andsobbing)",
  "Let me go! Let me go!",
  "Bastard!",
  "(screaming hysterically)",
  "- Babbit? - You fuckers!",
  "(mower)",
  "Speak into the microphone, squid brain!",
  "(man) Fuck!",
  "- Gimme your hand. - Fuck you!",
  "Gimme your other hand.",
  "There you go. You OK?",
  "Fuck!",
  "Oooh! God!",
  "No! Ow!",
  "Don't touch it! (screams)",
  "(screaming continues)",
  "lt's been paper targets up until today, huh?",
  "lt's no different, Johnny. Just a little more to clean up.",
  "You did all right today.",
  "You did real good.",
  "Goddamn son of a bitch!",
  "You're real cowboys, right! Batman and Robin!",
  "You know what this is, huh?",
  "Know what this is, punk?",
  "lt's two kees, uncut, crystal meth.",
  "Oh, shit!",
  "(FBl boss) Special Agent Utah, l'd like you to meet Agent Dietz.",
  "Works for the DEA. He was working deep cover until...",
  "You think l like this hair, man? Huh?",
  "You think l like these clothes?",
  "My wife wants me to stay at Ramada.",
  "l've been working on these fuckers for three months! THREE MONTHS!",
  "l finally got 'em to play Wheel Of Fortune with me so l can find out their supplier,...",
  "- ..and you fuckin' cowboys show up. - Nice tattoo, Dietz.",
  "You like that, Pappas? Fuck you.",
  "He has a record ofyour suspects' movements over the last three months.",
  "All l wanna know, smart guy, is how did they rob a bank on August  nd,...",
  "..when they were in Fort fuckin' Lauderdale August  nd?",
  "- Why don't you figure that out? - lt's not an easy thing to do, is it, Utah?",
  "You fuckin' jerks!",
  "Aw, shit!",
  "Shit!",
  "(buzzer)",
  "(buzzer)",
  "(groans)",
  "(insistent buzzing)",
  "Hey! Five foot wall's at Zero's. Let's go.",
  "Hey, Tyler.",
  "Hey, Bodhi!",
  "So, let's go!",
  "Time's a-wasting.",
  "- Now! - He does this.",
  "(excited whooping)",
  "You all right? You look like you saw a ghost.",
  "Forget aboutit, kid. They're ghosts.",
  "l gotta go.",
  "You gotta what?",
  "l forgot all about a meeting l have this morning.",
  "l gottajam. Sorry. Really. l'll call you later.",
  "So, l started trailing him.",
  "The Zen surf master?",
  "Bodhi, yeah. l'm on him all day, right?",
  "He goes to Tower Records, buys some CDs, has lunch at Patrick's Roadhouse,...",
  "..he goes into the Assured Trust Savings and Loan.",
  "Did he rob it?",
  "Cute! He's inside    minutes. The other guy, Roach, waited in the truck.",
  "They were scoping it out, right?",
  "Well, they were scoping it out or cashing a cheque.",
  "Wait. Then they go back home and they box up all their shit.",
  "See, summer's over.",
  "They load it in Bodhi's truck and they take it to a public storage unit.",
  "l lost them after that, but the house is empty. They're definitely outta here.",
  "Goddamn it! Why didn't you call me? They're probably halfway to Maui.",
  "Uh-uh, no. They've got to pick up some travelling money first.",
  "Assured Trust tomorrow, next day latest. l definitely got a feeling on this.",
  "Last time you had a feeling, l had to kill a guy.",
  "l hate that. lt looks bad on my report.",
  "Angelo, l'm right this time. We can still win this one.",
  "OK.",
  "Tomorrow morning, first thing, we'll be at the bank like stink on shit.",
  "(laughs) This Calvin and Hobbes is funny.",
  "Oranges, sir?",
  "- You want some oranges? - (Utah) No.",
  "No. We got a lot. No, thanks. Good luck.",
  "God!",
  "(laughs) ..for his turkey cemetery?!",
  "lt's time for lunch.",
  "Angelo, it's   .  !",
  "Around that corner is a sandwich shop. They sell meatball sandwiches.",
  "Best l've ever tasted. Would you go get me two?",
  "Come on, partner. Two.",
  "Thank you.",
  "Utah? Get me two.",
  "Hi. How ya doing?",
  "Hi. Two meatball sandwiches, a tuna on wheat and two lemonades, please.",
  "(woman) OK, that's two meatballs, one tuna on wheat,...",
  "..two lemonades. That's $ .  .",
  "- Thank you. - (woman) Uh-huh.",
  "(laughs) Oh, boy!",
  "God, you scared me!",
  "Here. Yours is the one that looks like a road kill.",
  "A road kill?",
  "- Enjoy. - Thank you very much.",
  "- Here's your lemonade. - Thanks.",
  "Did you see that Lincoln pull up?",
  "l'm so hungry l could eat the ass off a dead rhino. l should've asked for three.",
  "What Lincoln?",
  "Goddamn!",
  "FBl! Freeze!",
  "l got him! l got him!",
  "No!",
  "Freeze!",
  "(fires)",
  "Fuck!",
  "Get in! Get in!",
  "- Jesus Christ! - Go! Go!",
  "Go!",
  "Gimme a fuckin' break! l am going!",
  "- l don't see 'em! Where'd they go? - l don't fuckin' believe this!",
  "We're losing 'em!",
  "- You're losing 'em! - l'm not!",
  "Over to the right!",
  "- lt's coming up. - Punch it! Punch it! Punch it!",
  "- Where is he, Dick? - He's still behind us.",
  "(man) Hang on, you guys.",
  "This car's a piece of shit.",
  "Oh, shit!",
  "They're on the left!",
  "- l think we lost 'em. l can't see 'em. - Tell me where he is.",
  "Oh, fuck. Watch out!",
  "- We got you! - You ain't got shit!",
  "Damn it! Come on, come on!",
  "(engine splutters)",
  "OK, guys, emergency sanitation.",
  "Back up, buddy! Try it, man. Just try it.",
  "What about the old Chevy?",
  "- This guy down here. - l got him. l got the gun.",
  "- Get away from the car! Move it! - Get in.",
  "Wait, wait, wait.",
  "Don't do it, man. Don't be stupid. Run!",
  "Why's he taking so long?",
  "Come on!",
  "We gotta go now! What's his problem?",
  "Come on!",
  "(engine revs)",
  "- Let's go! - Oh! Shit!",
  "Fuck!",
  "(explosion)",
  "Look out!",
  "Hey!",
  "GET THE FUCK OUT OF THlS HOUSE!",
  "WHAT D'YOU THlNK YOU'RE DOlNG?",
  "HEY! HEY! HEY!",
  "(snarling)",
  "(yelp)",
  "(yells in pain)",
  "(howl ofrage)",
  "Say again,   .",
  "Roger that. Cal. plate -     Sam, lda, X-ray. Base out.",
  "Nothing?",
  "Nothing.",
  "Johnny, l wanna see you in my office right now.",
  "Unit   . See the manager,      Wilshire.",
  "l want you to know something. When you shoot, you don't miss.",
  "l missed.",
  "No. l believe you're either scared...",
  "..or you're getting too goddamn close to this surfing guru buddy ofyours.",
  "l don't believe you're scared.",
  "Hey, go home and get some rest. You look like hammered shit.",
  "lf l get anything that resembles your boy, l'll beep you.",
  "Now go home.",
  "(Angelo) Damn!",
  "(Tyler) What's the other guy look like?",
  "Never saw him. lt was a basic hit-and-run.",
  "You look like you got in a train wreck.",
  "Stupid jerkjust kept driving?",
  "Ouch! Baby, l'm sorry.",
  "Johnny, what is it with you? You've got that look again.",
  "As ifyou're about to tell me something and then you don't.",
  "Or you can't.",
  "There's something l want to tell you.",
  "lt's important. lt could really affect things between you and me.",
  "Man!",
  "This is harder than l thought.",
  "God, men are so bad at this.",
  "Shhh. Some other time.",
  "- You act like nothing happened! - Relax, Nathanial.",
  "Don't tell me to relax, Bodhi! He's a fucking federal agent!",
  "l should've shot him when l had the chance.",
  "l'll deal with that fuckin' cop.",
  "No, Rosie.",
  "We have hit    banks in three years and they haven't been able to touch us.",
  "All this does is up the stakes ofthe game.",
  "Fuck the stakes, Bodhi! The only person this is a game to is you. This is real!",
  "This is serious shit and l am scared. OK?",
  "So l say we get the fuck outta here now, tonight, OK?",
  "You run, you die.",
  "(Bodhi) Come on, think about it.",
  "This was never about money for us. lt was about us against the system.",
  "That system that kills the human spirit. We stand for something.",
  "To those dead souls inching along the freeways in their metal coffins,...",
  "..we show them that the human spirit is still alive.",
  "So, you trust me?",
  "OK.",
  "Then don't worry about this guy. l know exactly what to do with him.",
  "(gunshot)",
  "A lawyer!",
  "You lied to me!",
  "Tyler, put the gun down.",
  "l bet you lied about everything.",
  "l bet you lied about your parents!",
  "You just tell me the truth, Johnny.",
  "Did your parents die in a car accident?",
  "DlD THEY?!",
  "They live in Columbus, Ohio.",
  "l work Bank Robbery. The guys l'm after are surfers. l needed you at first,...",
  "- ..but after that... - Fuck you!",
  "Don't you have a soul?",
  "(drops gun)",
  "Goddamn you to hell!",
  "Tyler...",
  "TYLER, WAlT!",
  "TYLER!",
  "- (answering machine) Leave a message. - (Utah) Tyler, look, l fucked up. OK?",
  "l know l fucked up.",
  "l wanted to tell you, but l couldn't.",
  "l was afraid you'd leave. Good guess, huh ?",
  "Fuck! Why can't l ever say what l really mean?",
  "(Utah) llied to you. l'm an asshole, butlneedyou, Tyler.",
  "l wantyou to knowl've neverknown anyone like you before in mylife...",
  "..and lhope you change yourmind.",
  "(buzzer)",
  "Tyler, wait. l'm coming.",
  "Howdy, bro.",
  "So, come on, we're rollin'.",
  "What's going on, Bodhi?",
  "What happened? Cut yourself shaving?",
  "l don't think l wanna surf right now.",
  "Surf? No, this is really different, Johnny, you are gonna love it.",
  "So, we gotta get your stuff and get outta here.",
  "(Bodhi) OK. Uh, socks,...",
  "..shirt.",
  "Uh,... boots. Here we go.",
  "OK, put the stuff on in the truck. We gotta go. Life is short.",
  "You are gonna love this!",
  "Yo!",
  "All right, let's unload.",
  "- Take this, too. - Thank you, sir. There you go.",
  "Ever done this before?",
  "No, but l've seen it on TV.",
  "lt's    % pure adrenaline.",
  "Other guys snort for it, jab a vein for it. All you gotta do is jump.",
  "l'm sure it's a blast, but l screwed my knee up yesterday.",
  "Yeah, l noticed you limping, but don't worry cos we're not gonna land on land.",
  "Well, fine then. l feel so much better(!)",
  "OK, let's fly.",
  "Three minutes.",
  "This is a ceremony we always do at the end of the summer. One last speed star.",
  "By the way, you might wanna pull that little orange thing sometime.",
  "The life you save may be your own.",
  "So, uh... who packed my chute?",
  "l did. Why? You don't trust me?",
  "You gotta earn trust.",
  "OK, we'll earn it together. Here, take mine.",
  "Hey, Johnny, that's not a good idea.",
  "Bodhi's packs are pretty shitty. They only open about halfthe time.",
  "Less!",
  "Bullshit.",
  "Why don't you take young Grommet's? How'd that be?",
  "Nah, you don't want this one, man. This one's set for a neck-breaker.",
  "You'd probably be better offwith something like this.",
  "Are we gonnajump orjerk off?",
  "That's my man!",
  "Let's do it!",
  "You're about to jump out of a perfectly good aeroplane. How you feel about that?",
  "(joyful whooping)",
  "Shit! Whoa, shit!",
  "Whoa-ho-ho!",
  "Sex with the gods!",
  "You can't beat this!",
  "This is fucking beautiful!",
  "Whoo-hoo-hoo!",
  "Ha-ha!",
  "Whew!",
  "Whoa! Yeah! Yeah! Yeah!",
  "Hah!",
  "Come on, Johnny.",
  "That's it, Johnny. Go for it.",
  "Come on, Johnny!",
  "You can do it. Come on!",
  "Use your arms. Fly like an eagle, baby.",
  "Whoo!",
  "Keep coming.",
  "All right!",
  "- Johnny, you did it. - You're a speed star.",
  "We're going like a bat out o' hell.",
  "Whoo!",
  "How do you like it, Johnny?",
  "Amazing.",
  "Fucking amazing!",
  "This is so beautiful. l love this ground-rush shit.",
  "OK. Break!",
  "Great, isn't it?",
  "You're doing good.",
  "A thousand feet, pull.",
  "After you, Alphonse. l insist.",
  "Pull the ripcord now.",
  "You first.",
  "OK!",
  "Son of a bitch!",
  "(laughs)",
  "Jesus Christ.",
  "l gotta be losing it.",
  "lt's the closest you'll ever get to God.",
  "lt's like the palm ofyour hand, man. Zoom! Coming right at you.",
  "- Unbelievable. - Totally indescribable.",
  "- We did pull pretty low. - You'll never be the same again.",
  "- Didn't l tell you Johnny'd be just fine? - Yeah. Damn perf!",
  "Johnny, just drop your chute right there.",
  "Pack offyour shoulders.",
  "- Step back out of it. - l'll pack that for you, Bodhi.",
  "OK. Thanks.",
  "Johnny, come here. There's something you need to see.",
  "Hop in.",
  "OK.",
  "What's this?",
  "This is an insurance policy.",
  "lt will sting a bit, but it's for your own growth. Press play.",
  "(growls)",
  "Fuck you!",
  "(Tyler screams)",
  "(Tyler) FUCK YOU!",
  "She is a wild one, isn't she, Special Agent Utah?",
  "You're a fuckin' dead man!",
  "Hold it, man. Think it through, man.",
  "l'm the only one that knows where she is. l'm the only one,...",
  "..so let me talk. Let me talk.",
  "Talk.",
  "She'll be fine. Rosie won't do anything...",
  "..as long as l meet him at a certain place and time in six hours.",
  "You call him right now and tell him to let her go!",
  "Sorry, l can't do it, bro. They're on the road,...",
  "..and where they're going, there are no phones, so you are outta luck.",
  "(coughs)",
  "Oh, man.",
  "l hate this, Johnny. l really do.",
  "l hate violence.",
  "That's why l need Rosie. l could never do that.",
  "l could never hold a knife to Tyler's throat. She was my woman.",
  "We shared time.",
  "But Rosie is a... mechanism, you know?",
  "Once you set him in motion, he will not stop.",
  "He's, like, got this gift of blankness.",
  "But when three o'clock comes he will gut her like a pig...",
  "..and try not to get any on his shoes.",
  "There's nothing l can do about it unless l get there.",
  "So l guess that makes us partners...",
  "..because we both have the same goal: to get me where l need to go, right?",
  "We're wasting time.",
  "(laughs)",
  "That's what l love about you, Johnny. You are just as sharp as a razor.",
  "Murphy, take the plane down to Santa Monica, top up the tanks.",
  "- OK, you guys, it's party time. Move it! - Right. We're on it.",
  "All l'm asking for is    seconds ofyour life, Johnny.",
  "You see? lt's basic dog psychology.",
  "lf you scare them and get them peeing down their leg, they submit.",
  "Yet ifyou project weakness, you draw aggression. That's how people get hurt.",
  "You see, fear causes hesitation...",
  "..and hesitation will cause your worst fears to come true.",
  "So it's simple. You project strength to avoid conflict.",
  "Peace through superior firepower.",
  "Oh...",
  "There. Can't have you walking through those doors with your dick in your hand.",
  "l can't do this.",
  "Sure you can.",
  "Who knows? You might like it. lt's a killer rush.",
  "Bodhi, this is your fuckin' wake-up call, man!",
  "l am an FBl agent!",
  "l know, man. lsn't it wild?",
  "But that's what makes it great, Johnny.",
  "We can exist on a different plane, we can make our own rules.",
  "Why be a servant to the law when you can be its master?",
  "Fuckin' A!",
  "l love this fuckin' job.",
  "OK,    seconds, door to door.",
  "lt's a small price to pay for someone who loves you.",
  "She does, you know?",
  "lt's not her style to fall so hard. l don't think she did with me.",
  "OK, Mr Carter.",
  "LBJ.",
  "Mr Nixon.",
  "Well, sorry, Johnny. Looks like you don't get to be president!",
  "l'm ready.",
  "Rock and roll!",
  "Everybody freeze!",
  "- OK. On the floor now! - On the floor right now! Do it.",
  "Hold it! Where you going?",
  "Everybody down! Let's go!",
  "(Utah) On the floor, asshole!",
  "l'll blow out your fuckin' kneecaps, then you'll be on the floor.",
  "A kick in the ass, ain't it, man?",
  "Hey, look. You're on TV. Smile.",
  "Could be a little hard to play FBl now, huh?",
  "Can we just get the goddamned money and get out of here!",
  "Nobody move. Heads down, eyes down.",
  "Good afternoon, ladies and gentlemen. May l have your attention, please?",
  "We are the Ex-Presidents and, as you can see, we are, in fact, robbing your bank.",
  "So with a little co-operation l won't have to blow your heads off.",
  "So l need just a couple of minutes of your lives and we're gone.",
  "Dick, go to the vault.",
  "Uh... you, Miss Jennings, would you be a dear and open the gate for my associate?",
  "Mr Duggan's got the keys.",
  "We never go to the vault!",
  "Just do it!",
  "Lyndon, go with them. Get in the vault, man. Go! Go!",
  "Who's Mr fuckin' Duggan?!",
  "Mr Duggan, do you wanna open the vault or do you want me to do it?",
  "Do whatever they want, Teri.",
  "Take the fucking keys! Take 'em!",
  "Move it!",
  "Open the damned door!",
  "l'll fuckin' blow your fuckin' head off! Move it!",
  "Come on! Come on!",
  "Get outta the way!",
  "OK. All right.",
  "Go for the big bag.",
  "What we doin' in a fuckin' vault?!",
  "This is a bad idea.",
  "- (screams) - On the ground. Don't look at me!",
  "You're blowing it, man. You're breaking your own rules and pulling too much time.",
  "Jimmy, how we doing?",
  "  . What's happening?",
  "Don't worry, man, it's fine. lt's great.",
  "Fuck! Fuck!",
  "(Hey, l'm a cop.)",
  "OK!",
  "Son of a bitch!",
  "(laughs)",
  "Jesus Christ.",
  "l gotta be losing it.",
  "lt's the closest you'll ever get to God.",
  "lt's like the palm ofyour hand, man. Zoom! Coming right at you.",
  "- Unbelievable. - Totally indescribable.",
  "- We did pull pretty low. - You'll never be the same again.",
  "- Didn't l tell you Johnny'd be just fine? - Yeah. Damn perf!",
  "Johnny, just drop your chute right there.",
  "Pack offyour shoulders.",
  "- Step back out of it. - l'll pack that for you, Bodhi.",
  "OK. Thanks.",
  "Johnny, come here. There's something you need to see.",
  "Hop in.",
  "OK.",
  "What's this?",
  "This is an insurance policy.",
  "lt will sting a bit, but it's for your own growth. Press play.",
  "(growls)",
  "Fuck you!",
  "(Tyler screams)",
  "(Tyler) FUCK YOU!",
  "She is a wild one, isn't she, Special Agent Utah?",
  "You're a fuckin' dead man!",
  "Hold it, man. Think it through, man.",
  "l'm the only one that knows where she is. l'm the only one,...",
  "..so let me talk. Let me talk.",
  "Talk.",
  "She'll be fine. Rosie won't do anything...",
  "..as long as l meet him at a certain place and time in six hours.",
  "You call him right now and tell him to let her go!",
  "Sorry, l can't do it, bro. They're on the road,...",
  "..and where they're going, there are no phones, so you are outta luck.",
  "(coughs)",
  "Oh, man.",
  "l hate this, Johnny. l really do.",
  "l hate violence.",
  "That's why l need Rosie. l could never do that.",
  "l could never hold a knife to Tyler's throat. She was my woman.",
  "We shared time.",
  "But Rosie is a... mechanism, you know?",
  "Once you set him in motion, he will not stop.",
  "He's, like, got this gift of blankness.",
  "But when three o'clock comes he will gut her like a pig...",
  "..and try not to get any on his shoes.",
  "There's nothing l can do about it unless l get there.",
  "So l guess that makes us partners...",
  "..because we both have the same goal: to get me where l need to go, right?",
  "We're wasting time.",
  "(laughs)",
  "That's what l love about you, Johnny. You are just as sharp as a razor.",
  "Murphy, take the plane down to Santa Monica, top up the tanks.",
  "- OK, you guys, it's party time. Move it! - Right. We're on it.",
  "All l'm asking for is    seconds ofyour life, Johnny.",
  "You see? lt's basic dog psychology.",
  "lf you scare them and get them peeing down their leg, they submit.",
  "Yet ifyou project weakness, you draw aggression. That's how people get hurt.",
  "You see, fear causes hesitation...",
  "..and hesitation will cause your worst fears to come true.",
  "So it's simple. You project strength to avoid conflict.",
  "Peace through superior firepower.",
  "Oh...",
  "There. Can't have you walking through those doors with your dick in your hand.",
  "l can't do this.",
  "Sure you can.",
  "Who knows? You might like it. lt's a killer rush.",
  "Bodhi, this is your fuckin' wake-up call, man!",
  "l am an FBl agent!",
  "l know, man. lsn't it wild?",
  "But that's what makes it great, Johnny.",
  "We can exist on a different plane, we can make our own rules.",
  "Why be a servant to the law when you can be its master?",
  "Fuckin' A!",
  "l love this fuckin' job.",
  "OK,    seconds, door to door.",
  "lt's a small price to pay for someone who loves you.",
  "She does, you know?",
  "lt's not her style to fall so hard. l don't think she did with me.",
  "OK, Mr Carter.",
  "LBJ.",
  "Mr Nixon.",
  "Well, sorry, Johnny. Looks like you don't get to be president!",
  "l'm ready.",
  "Rock and roll!",
  "Everybody freeze!",
  "- OK. On the floor now! - On the floor right now! Do it.",
  "Hold it! Where you going?",
  "Everybody down! Let's go!",
  "(Utah) On the floor, asshole!",
  "l'll blow out your fuckin' kneecaps, then you'll be on the floor.",
  "A kick in the ass, ain't it, man?",
  "Hey, look. You're on TV. Smile.",
  "Could be a little hard to play FBl now, huh?",
  "Can we just get the goddamned money and get out of here!",
  "Nobody move. Heads down, eyes down.",
  "Good afternoon, ladies and gentlemen. May l have your attention, please?",
  "We are the Ex-Presidents and, as you can see, we are, in fact, robbing your bank.",
  "So with a little co-operation l won't have to blow your heads off.",
  "So l need just a couple of minutes of your lives and we're gone.",
  "Dick, go to the vault.",
  "Uh... you, Miss Jennings, would you be a dear and open the gate for my associate?",
  "Mr Duggan's got the keys.",
  "We never go to the vault!",
  "Just do it!",
  "Lyndon, go with them. Get in the vault, man. Go! Go!",
  "Who's Mr fuckin' Duggan?!",
  "Mr Duggan, do you wanna open the vault or do you want me to do it?",
  "Do whatever they want, Teri.",
  "Take the fucking keys! Take 'em!",
  "Move it!",
  "Open the damned door!",
  "l'll fuckin' blow your fuckin' head off! Move it!",
  "Come on! Come on!",
  "Get outta the way!",
  "OK. All right.",
  "Go for the big bag.",
  "What we doin' in a fuckin' vault?!",
  "This is a bad idea.",
  "- (screams) - On the ground. Don't look at me!",
  "You're blowing it, man. You're breaking your own rules and pulling too much time.",
  "Jimmy, how we doing?",
  "  . What's happening?",
  "Don't worry, man, it's fine. lt's great.",
  "Fuck! Fuck!",
  "(Hey, l'm a cop.)",
  "(So?)",
  "(l'm a cop.)",
  "(No,... don't.)",
  "(You got a gun on your ankle?)",
  "(Yeah.)",
  "(When l make a move, you back me up.)",
  "- (Please, don't. You don't have to.) - (You'll back me up.)",
  "(Don't do it. Don't do anything.)",
  "(No, don't! Don't!)",
  "(Please, put it away. Please, put it away. Put it away.)",
  "Hurry up!",
  "Let's go, we gotta go!",
  "Fuckin' move!",
  "(woman screams)",
  "Federal agent. Undercover!",
  "(screaming)",
  "Nobody fuckin' move!",
  "(whimpers)",
  "You OK? Hang on, little bro.",
  "Come on, we are outta here. We are outta here.",
  "Hang on, little brother. Just hang on, man.",
  "No, man. No!",
  "(stops breathing)",
  "Are you outta your fuckin' mind?",
  "What's the matter with you?! ls that what you want? Did you get what you wanted?",
  "You can't take him with. LET'S GO!",
  "Goddamn it, who's in charge ofthis camera crew? This is a crime-scene area!",
  "Get 'em the fuck outta here!",
  "You have the right to remain silent.",
  "Anything you say, can and will be used against you in a court of law.",
  "lf you so desire, an attorney will be provided for you, free of cost.",
  "Do you understand these rights l've just given you, Utah?",
  "D'you understand! Understand the rights l've just read you, Utah?!",
  "He understands his goddamned rights! Jesus Christ, kid, are you OK?",
  "Stand up. Get these cuffs off him.",
  "Leave 'em on! Your partner's an accessory to murder, you understand?",
  "There are three dead people. One's a police officer.",
  "Let me show you something, pal. How does that sit in your stomach?",
  "Take your hands off me right now.",
  "Come on.",
  "Listen, look at me. Look at me!",
  "Don't send him in with the black and whites, let me ride him in.",
  "Yeah, sure, Angelo, why not?",
  "That's why l put you two together to begin with.",
  "You deserve each other. You're just as bad as he is...",
  "..only you're a little fatter, slower and more pathetic.",
  "lt's like the blind leading the blind.",
  "Harp, l was in this Bureau when you were still popping zits on your funny face...",
  "..and jackin' offto the lingerie section of the Sears catalogue!",
  "ls that right, Pappas?",
  "Yes, that's right, and there's one thing l've learnt that you still haven't got.",
  "Oh, yeah? Why don't you astonish me, shit face?",
  "Respect for my elders, plain and simple.",
  "- Come on, kid, let's go. - (man) Holy shit.",
  "l know where they're going.",
  "l figured you did.",
  "Santa Monica airport. Fast! But we've got one minor problem.",
  "What?",
  "We can't arrest them or shoot them.",
  "What?!",
  "(brakes screech)",
  "Did you set the altimeter?",
  "- One thousand. - What?",
  "One thousand.",
  "Check the rigging, OK?",
  "Whoa, whoa, whoa.",
  "Fuckin' FBl.",
  "l'm not armed.",
  "(cocks gun)",
  "But you're not alone.",
  "Good guess.",
  "There's a gun on you right now.",
  "Where's Roach?",
  "He's around somewhere.",
  "Listen, Johnny, we are in kind of a hurry. What do you need?",
  "You gotta tell me where she is.",
  "And let my policy expire? Good idea.",
  "Look, Bodhi, people are dead. The ride is over.",
  "Oh, no, no. l say when it's over.",
  "The guy you killed was an off-duty cop. They'll nail you wherever you land.",
  "There's a new thing called radar. Maybe you've heard of it.",
  "- What is your... - (engine)",
  "Nathanial, get in there.",
  "(Nathanial) Get back in the cockpit. Move!",
  "l know you, man.",
  "When they fall on you, you won't back down.",
  "They'll have to burn your ass to the ground!",
  "Uh-huh. And shit happens.",
  "Look, you got a death wish, fine, but don't take Tyler with you.",
  "l'm begging you.",
  "Tell me where she is, then l walk away.",
  "You walk away?",
  "l walk away.",
  "That is beautiful, Johnny.",
  "ANGELO, DON'T FlRE!",
  "THEY'LL KlLL HER. NO!",
  "Get out ofthe way, kid! Goddamn it!",
  "Damn.",
  "NOOOOO!",
  "Jesus Christ!",
  "- Angelo. - l don't have much...",
  "- Come on, man, just hang on. - l really fucked up.",
  "Just hang on. You'll be all right.",
  "l'm not flying you guys to San Felipe.",
  "- Get in the plane. Start those engines. - Good(!) Tell him where we're going.",
  "Let's go, man.",
  "We are gonna ride this all the way, Johnny, you and me. So let's go.",
  "Get the fuck up! Tyler's waiting.",
  "Start the engines now!",
  "(sirens)",
  "Go!",
  "GO! GO! GO! GO! GO!",
  "Rosie? Yo, Rosie, this is Air Force One. Do you read me? Do you read me? Over.",
  "Look, we've been over Mexico for the last half-hour.",
  "Can l quit mowing the lawn here?",
  "Getting more bushes in the wheels than l usually like.",
  "Shut your mouth and take it to      feet on this heading, all right?",
  "l don't think that's such a good idea, man. We'll pop up on their screens.",
  "Doesn't matter, we're almost there. Just gotta get you to a safe jump altitude.",
  "Let's get your rig on.",
  "Hey, man, l'm cold. Really cold.",
  "l'll get yourjacket. Here's yourjacket. Easy.",
  "Oh, fuck!",
  "l know, l know, l know.",
  "Easy. Easy. One arm at a time.",
  "l can't get it, l can't get it.",
  "(coughs)",
  "No, man! No, no, no!",
  "Johnny, throw me that money bag.",
  "NOW!",
  "You're cold because all the blood is running out ofyour body, Roach.",
  "You're going to be dead soon.",
  "l hope it was worth it.",
  "Don't listen to him, he's just scared.",
  "Just keep thinking about all those senoritas and margaritas...",
  "..that are gonna nurse you back to health, OK?",
  "What the fuck are you looking at?",
  "There you go.",
  "Rosie! Rosie, this is Air Force One. Do you copy? Do you copy? Over.",
  "(Rosie) Copy. We have a visual on you.",
  "Tell him to release Tyler.",
  "Do it! Do it now!",
  "You won, you got what you wanted.",
  "What ifyour chute fails? Cancel the order.",
  "She's served her purpose.",
  "Do it, man. You owe me that much.",
  "- OK, you ready? - Yeah.",
  "On three.",
  "One, two,... three.",
  "Easy. Come on, a little more.",
  "- Get your chute clear. OK? - OK.",
  "l'll see you on the ground, all right?",
  "l'll see you in hell, Johnny.",
  "Oh!",
  "l know it's hard for you. You want me so bad it's like acid in your mouth,...",
  "..but not this time.",
  "Adios, amigo.",
  "Fucker!",
  "God! Wha...?",
  "- Pull the chute, Bodhi. - You are crazy.",
  "- Pull the fuckin' chute! - Why don't you pull it?",
  "No games, Bodhi! Pull the cord now!",
  "Nah, you pull it.",
  "Go ahead, Johnny, pull it.",
  "You gotta drop the gun, right?",
  "lf you use your other hand, what you gonna hold on with?",
  "Pull it right now, or l blow your fuckin' head off and pull it myself.",
  "- lt's the only way it's gonna happen. Do it. - Swear to God, l will.",
  "Do it, man, or you're gonna die, Johnny.",
  "Six seconds, we're gonna be meat waffles.",
  "Five... four...",
  "- You're fuckin' crazy! PULL lT! PULL lT! - ..three... two...",
  "- ..one... - Shit!",
  "Shit!",
  "(both shout)",
  "(coughs)",
  "Jesus Christ, Bodhi.",
  "God.",
  "Damn, you are one radical son of a bitch.",
  "l'm outta here, Johnny.",
  "(yells in pain)",
  "(screams)",
  "That knee again, huh?",
  "Too bad. Looks like this time you won't be getting your man.",
  "This game we both lose.",
  "Let her go.",
  "Let her go!",
  "Johnny, l...",
  "Shh. Some other time.",
  "Come on, we're out of here.",
  "Yo, Johnny!",
  "l'll see you in the next life!",
  "(whoops)",
  "l can't leave him. We gotta bury him.",
  "There's no time, man.",
  "(radio) ..the cyclone warning is for coastal areas between Torquayand Cape Ottway.",
  "Experts are saying this couldbe one of the worststorms in Australia's history.",
  "Heavy rains will continue into the night...",
  "..with destructive winds reaching up to    km perhour.",
  "The centre ofthe cyclone is now expected to cross the coast...",
  "..at Bells Beach early tomorrowmorning.",
  "Residents are advised to prepare for evacuation.",
  "(man) What d'you wanna do now?",
  "l wanna get out ofthis wet. l'm freezing.",
  "Sorry, mate.",
  "Anybody been out there?",
  "No-one's been out and no-one's going out.",
  "You gotta be fucking crazy, man. Death-on-a-stick out there, mate.",
  "Coming down, man.",
  "(surf thunders)",
  "Lose something, bro?",
  "Special Agent Utah. l knew l could count on you.",
  "l've been to every city in Mexico.",
  "Came across an unclaimed piece of meat in Baja, turned out to be Rosie.",
  "Guess he picked a knife fight with somebody better.",
  "Found a passport ofyours in Sumatra, missed you by about a week in Fiji.",
  "But l knew you wouldn't miss a   -year storm, Bodhi.",
  "Yeah.",
  "Too bad. You finally get your waves and it's totally closed out.",
  "Just waiting for my set.",
  "You gotta go down.",
  "You crossed the line and people trusted you and they died.",
  "Yeah, it went bad, went real bad.",
  "Life sure has a sick sense of humour, doesn't it?",
  "- Still surfing? - Every day.",
  "Come on, Bodhi. lt's time to go.",
  "You know you gotta go back with me.",
  "(laughs)",
  "Sorry, my friend.",
  "Come on!",
  "SHlT! NO!",
  "NO!!",
  "l told them...",
  "..you'd go quietly.",
  "(helicopter)",
  "NO!",
  "You know there's no way l can handle a cage, man.",
  "l don't care. You gotta go down.",
  "lt's gotta be that way.",
  "OK, man. OK.",
  "l'm screwed.",
  "l'm gonna go to jail and l'll pay, and Johnny Utah gets his guy. Right?",
  "Good for you. That's real good.",
  "You're gonna be a big hero now.",
  "But look at it, Johnny. Look at it!",
  "This is a once-in-a-lifetime opportunity, man.",
  "Just let me go out there, let me get one wave before you take me. One wave.",
  "Where am l gonna go, man?",
  "Cliffs on both side. l'm not gonna paddle to New Zealand!",
  "My whole life has been about this moment, Johnny.",
  "Come on, compadre.",
  "Come on.",
  "COME ON!",
  "Via con Dios!",
  "What the fuck, Utah?",
  "You let him go!",
  "No, l didn't.",
  "No way! The guy's nuts.",
  "We'll get him when he comes back in.",
  "He's not coming back."
]